name: Build Front

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/build-api.yml"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/build-api.yml"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
  VITE_IMAGEKIT_URL_ENDPOINT: ${{ secrets.VITE_IMAGEKIT_URL_ENDPOINT }}
  VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
  VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ github.workspace }}/api:${{ github.ref_name }}
          build-args: |
            VITE_API_URL=${{ env.VITE_API_URL }}
            VITE_MAPBOX_TOKEN=${{ env.VITE_MAPBOX_TOKEN }}
            VITE_IMAGEKIT_URL_ENDPOINT=${{ env.VITE_IMAGEKIT_URL_ENDPOINT }}
            VITE_SERVER_URL=${{ env.VITE_SERVER_URL }}
            VITE_GOOGLE_MAPS_API_KEY=${{ env.VITE_GOOGLE_MAPS_API_KEY }}
